"""init schema

Revision ID: 2ccda2f64e09
Revises: 
Create Date: 2026-03-03 19:42:54.807656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ccda2f64e09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('scorekeeper_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('nut_enabled', sa.Boolean(), nullable=False),
    sa.Column('skunk_enabled', sa.Boolean(), nullable=False),
    sa.Column('track_bid_trail', sa.Boolean(), nullable=False),
    sa.Column('digit_order_mode', sa.String(length=50), nullable=False),
    sa.Column('base_bet', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scorekeeper_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('winner_user_id', sa.UUID(), nullable=True),
    sa.Column('loser_user_id', sa.UUID(), nullable=True),
    sa.Column('final_bid_count', sa.Integer(), nullable=True),
    sa.Column('final_bid_digit', sa.Integer(), nullable=True),
    sa.Column('final_bid_raw', sa.String(length=20), nullable=True),
    sa.Column('is_nut', sa.Boolean(), nullable=False),
    sa.Column('is_skunk', sa.Boolean(), nullable=False),
    sa.Column('amount_won', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['loser_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bid_order', sa.Integer(), nullable=False),
    sa.Column('bid_count', sa.Integer(), nullable=False),
    sa.Column('bid_digit', sa.Integer(), nullable=False),
    sa.Column('bid_raw', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hand_bids')
    op.drop_table('hands')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
