"""add hand money flags

Revision ID: 914d718284e9
Revises: 3dc83971e682
Create Date: 2026-03-03 20:50:42.445532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914d718284e9'
down_revision: Union[str, Sequence[str], None] = '3dc83971e682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hand_bids', sa.Column('bet_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('hand_bids', sa.Column('is_nut', sa.Boolean(), nullable=False))
    op.add_column('hand_bids', sa.Column('is_skunk', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hand_bids', 'is_skunk')
    op.drop_column('hand_bids', 'is_nut')
    op.drop_column('hand_bids', 'bet_amount')
    # ### end Alembic commands ###
