"""add hand betting fields

Revision ID: c461d10d4485
Revises: 914d718284e9
Create Date: 2026-03-03 21:03:25.642340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c461d10d4485'
down_revision: Union[str, Sequence[str], None] = '914d718284e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hand_bids', 'bet_amount')
    op.add_column('hands', sa.Column('bet_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'bet_amount')
    op.add_column('hand_bids', sa.Column('bet_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
