"""add game presets

Revision ID: db4e93559a06
Revises: c461d10d4485
Create Date: 2026-03-06 11:49:19.510927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4e93559a06'
down_revision: Union[str, Sequence[str], None] = 'c461d10d4485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cards_per_hand', sa.Integer(), nullable=False),
    sa.Column('base_bet', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nut_enabled', sa.Boolean(), nullable=False),
    sa.Column('skunk_enabled', sa.Boolean(), nullable=False),
    sa.Column('track_bid_trail', sa.Boolean(), nullable=False),
    sa.Column('digit_order_mode', sa.String(length=64), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_presets')
    # ### end Alembic commands ###
